### ISSUE TITLE
docker compose prompted error: no configuration file provided: not found

### ISSUE THREAD

**Issue by elhaddajiOtmane** [vguleaev/React-Express-Mongo-Docker-tutorial#12]
![Screenshot 2023-05-12 094219](https://github.com/vguleaev/React-Express-Mongo-Docker-tutorial/assets/39245156/3d1d2129-04bd-4263-82ad-c72f46629824)

**Comment by ldrahnik** [comment]
@elhaddajiOtmane Hello there, try to run the command `docker-compose -f docker-compose.yml logs` or more simply `docker-compose logs` because file arg `-f` is recommended/required to use only when is file not found automatically otherwise is useless.
